### ISSUE TITLE
Missing images for orange pi 5 Plus

### ISSUE THREAD

**Issue by TheiLLeniumStudios** [si0ls/talos-orangepi5#2]
Hi,

As the title says, there doesn't seem to be any Orange Pi 5 Plus images published in the v1.0 release. Is that intended?

If so, is there a way I can specifically build 5 Plus images from source? I saw the makefile and it only seems to be building for the Orange Pi 5. Any help on building them would be appreciated

**Comment by schneid-l** [comment]
Oh yes, it's not obvious
The OPI5 image should work for both as both device tree blobs are included
I'll update the Readme to make it clear ;)

Don't hesitate to tell me if it does not work

**Comment by TheiLLeniumStudios** [comment]
Oh perfect. I'll try that now. I had a 6 Node K0S cluster running (with Ubuntu as OS) on OP5P's and had been waiting for someone to implement Talos support for the device. Great work!

Just another small correction in the readme, it says the file extension for the raw image is `xz` whereas the compressed images in the release are `zst` compressed. Not a big thing but someone who's blindly copy pasting from the Readme might not like that :)

**Comment by schneid-l** [comment]
Yes, I also have a 6 node cluster with k3s, I waited for someone to implement but I had to do it ahah

Thanks for the feedback I will fix it
