### ISSUE TITLE
Request: support for Orange Pi 5 Max

### ISSUE THREAD

**Issue by zendes** [si0ls/talos-orangepi5#3]
Hi. Could you comment on how much effort it would be to add support for the [Orange Pi 5 Max](http://www.orangepi.org/html/hardWare/computerAndMicrocontrollers/details/Orange-Pi-5-Max.html)? The board is similar to the Plus (RK3588 & 2.5G ethernet, but uses LPDDR5 RAM). Is this something you'd be interested in working on?

I'm looking for a few SBC boards for a project, and RK3588 seems more interesting than an RPI5. The problem is always software, and projects like this help with filling that gap. Thanks!

**Comment by schneid-l** [comment]
Hi 👋
Sorry for my late answer.

The missing thing for OPI 5 Max is the Device Tree

It's not available in mainline kernel nor the Collabora one used here.

Seems like Armbian maintained kernel [provides the OPI5 Max dtb](https://github.com/armbian/linux-rockchip/blob/rk-6.1-rkr3/arch/arm64/boot/dts/rockchip/rk3588-orangepi-5-max.dts) but I was not able to make the Armbian kernel successfully boot with Talos.

If you're willing to try to compile and boot Talos with the Armbian kernel it could work

**Comment by zendes** [comment]
Thanks. I'll go take a look
